#!/usr/bin/env bash
UNAME=`id -nu 1000`
BASE='/usr/share/silverred/files'
EBASE="${BASE//\//\\\/}"

find $BASE -type f -exec bash -c '
TARGET=`echo {} | sed "s/'$EBASE'//"`
MODDED=`cat {} | sed "s/<..name..>/'$UNAME'/"`
if [ ! -f $TARGET ] || ! echo "$MODDED" | diff $TARGET -; then
   echo "$MODDED" > $TARGET
fi' \;
